### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by maxsalven** [oliver-ni/prefixed_id#1]
Elixir 1.17.3 (compiled with Erlang/OTP 27)
MacOS 15.1
Apple M1 Max

```
==> prefixed_id
Compiling 2 files (.ex)

== Compilation error in file lib/prefixed_id/nifs.ex ==
** (ErlangError) Erlang error: :enoent
    (elixir 1.17.3) lib/system.ex:1114: System.cmd("cargo", ["metadata", "--format-version=1"], [cd: "native/prefixed_id"])
    (rustler 0.33.0) lib/rustler/compiler/config.ex:76: Rustler.Compiler.Config.metadata!/1
    (rustler 0.33.0) lib/rustler/compiler/config.ex:63: Rustler.Compiler.Config.build/1
    (rustler 0.33.0) lib/rustler/compiler.ex:8: Rustler.Compiler.compile_crate/3
    lib/prefixed_id/nifs.ex:6: (module)
could not compile dependency :prefixed_id, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile prefixed_id --force", update it with "mix deps.update prefixed_id" or clean it with "mix deps.clean prefixed_id"
```

**Comment by maxsalven** [comment]
Looks like I need rust installed to compile this; apologies, wasn't familiar with packages that require it.
